<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


$viewModel = $block->getData('view_model_tab1');

?>

<h1>title</h1>
<?php echo $viewModel->getProductos('Parametro'); ?>
<hr>
<form id="form_id" >
    <input type="text" id="field1" name="field1" value="one" />
    <input type="text" id="field2" name="field2" value="two" />
    <button type="submit">Send!</button>
</form>

<script type="text/javascript">
require([
    "jquery",
    "mage/mage"
],function($) {
    $(document).ready(function() {
        $('#form_id').mage(
            'validation',
            {
                submitHandler: function(form) {
                    var customurl = "<?php echo $this->getUrl().'sacsicustomer/newtab/productos'?>";
                    $.ajax({
                        url:  customurl,
                        data: $('#form_id').serialize(),
                        type: 'POST',
                        dataType: 'json',
                        beforeSend: function() {
                            // show some loading icon
                            console.log("show some loading icon");
                        },
                        success: function(data, status, xhr) {
                            // data contains your controller response
                            console.log(data, status, xhr);
                            debugger;
                        },
                        error: function (xhr, status, errorThrown) {
                            console.log('Error happens. Try again.');
                            console.log(errorThrown);
                        }
                    });
                }
            }
        );
    });
});

