version: "3"

services:
  db:
    container_name: m242_db
    image: mysql
    volumes:
      - $PWD/docker/db/scripts/:/docker-entrypoint-initdb.d
      - $PWD/docker/db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: magento_242
    ports:
      - "3306:3306"
  web:
    container_name: m242_web
    depends_on:
      - db
    build:
      context: $PWD/docker/web/.
    volumes:
      - $PWD/src:/var/www/html
      - $PWD/docker/web/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - $PWD/docker/web/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    container_name: m242_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    # restart: always
    ports:
      - 8080:80

  elasticsearch:
    build:
      context: $PWD/docker/elasticsearch/.
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    logging:
      driver: "none"

  redis:
    image: redis
    ports:
      - "6379:6379"

#volumes:
#   redisinsight:
#   dbdata:
#   rabbitmqdata:
